"""Convert the Noto TTFs we already ship (for PDFs) into woff2 web fonts.

Run: uv run --no-project --with "fonttools[woff]" python scripts/build-webfonts.py

Why not next/font/google: that downloads font CSS from Google at build time, so a build
without internet fails and every deployment depends on a third party. The same faces are
already in the repo for the loan-file PDF, so the web app self-hosts those instead — one
source of truth for type, an offline-capable build, and no third-party request at runtime.

Each face is subsetted to the characters its script actually needs (plus Latin digits and
punctuation, which every Indian-language screen mixes in), which is what keeps them small
enough for a 2G connection.
"""

import shutil
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "services" / "core" / "assets" / "fonts"
OUT = ROOT / "apps" / "web" / "src" / "app" / "fonts"

# Unicode ranges per script, as CSS unicode-range strings (also used for the @font-face rules).
COMMON = "U+0000-00FF,U+2000-206F,U+20B9,U+2212,U+25CC"  # Latin, punctuation, ₹, dotted circle
SCRIPTS: dict[str, tuple[str, str]] = {
    "latin": ("NotoSans", COMMON),
    "devanagari": ("NotoSansDevanagari", f"U+0900-097F,U+A8E0-A8FF,{COMMON}"),
    "bengali": ("NotoSansBengali", f"U+0980-09FF,{COMMON}"),
    "gujarati": ("NotoSansGujarati", f"U+0A80-0AFF,{COMMON}"),
    "gurmukhi": ("NotoSansGurmukhi", f"U+0A00-0A7F,{COMMON}"),
    "kannada": ("NotoSansKannada", f"U+0C80-0CFF,{COMMON}"),
    "malayalam": ("NotoSansMalayalam", f"U+0D00-0D7F,{COMMON}"),
    "oriya": ("NotoSansOriya", f"U+0B00-0B7F,{COMMON}"),
    "tamil": ("NotoSansTamil", f"U+0B80-0BFF,{COMMON}"),
    "telugu": ("NotoSansTelugu", f"U+0C00-0C7F,{COMMON}"),
    "arabic": ("NotoNaskhArabic", f"U+0600-06FF,U+0750-077F,U+FB50-FDFF,U+FE70-FEFF,{COMMON}"),
}
WEIGHTS = {"Regular": 400, "Bold": 700}


def ranges_to_codepoints(spec: str) -> list[int]:
    points: list[int] = []
    for part in spec.split(","):
        part = part.strip().removeprefix("U+")
        if "-" in part:
            start, end = part.split("-")
            points.extend(range(int(start, 16), int(end, 16) + 1))
        else:
            points.append(int(part, 16))
    return points


def build() -> int:
    if not SOURCE.exists():
        print(f"missing font sources at {SOURCE}", file=sys.stderr)
        return 1
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    total = 0
    for script, (family, unicode_range) in SCRIPTS.items():
        for style in WEIGHTS:
            src = SOURCE / f"{family}-{style}.ttf"
            if not src.exists():
                print(f"skip {src.name}: not shipped", file=sys.stderr)
                continue
            font = TTFont(src)
            options = subset.Options(
                layout_features=["*"],  # Indic shaping needs its GSUB/GPOS features intact
                drop_tables=["FFTM"],
                notdef_outline=True,
                recalc_bounds=True,
                flavor="woff2",
            )
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=ranges_to_codepoints(unicode_range))
            subsetter.subset(font)
            target = OUT / f"{script}-{WEIGHTS[style]}.woff2"
            font.flavor = "woff2"
            font.save(target)
            font.close()
            total += target.stat().st_size
            print(f"{target.name:28} {target.stat().st_size / 1024:6.1f} KB")

    (OUT / "README.md").write_text(
        "Generated by scripts/build-webfonts.py from services/core/assets/fonts (Noto, SIL Open Font License).\n"
        "Do not edit by hand; re-run the script if the source faces change.\n",
        encoding="utf-8",
    )
    print(f"total {total / 1024:.0f} KB across {len(list(OUT.glob('*.woff2')))} faces")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
