// Renders the brand mark into the PNG sizes a PWA install needs (Android requires PNG).
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const svg = await readFile(join(root, 'public', 'icon.svg'));
const out = join(root, 'public', 'icons');
await mkdir(out, { recursive: true });

for (const size of [192, 512]) {
  await sharp(svg).resize(size, size).png().toFile(join(out, `icon-${size}.png`));
}
// Maskable: the safe zone is the middle 80%, so pad the mark and fill the brand colour.
for (const size of [192, 512]) {
  const inner = Math.round(size * 0.8);
  const pad = Math.round((size - inner) / 2);
  await sharp(await sharp(svg).resize(inner, inner).png().toBuffer())
    .extend({ top: pad, bottom: pad, left: pad, right: pad, background: '#0B3D91' })
    .png()
    .toFile(join(out, `maskable-${size}.png`));
}
await writeFile(join(out, 'README.md'), 'Generated by scripts/build-icons.mjs from public/icon.svg. Do not edit by hand.\n');
console.log('wrote 4 icons to public/icons');
