// Regenerates src/tokens.css from src/tokens.ts (run after editing tokens).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ts = readFileSync(join(here, '../src/tokens.ts'), 'utf8');
const block = (name) => {
  const start = ts.indexOf(`${name}: {`);
  return [...ts.slice(start, ts.indexOf('}', start)).matchAll(/(\w+): '(#[0-9A-Fa-f]{6})'/g)].map((m) => [m[1], m[2]]);
};
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const vars = (pairs, indent) => pairs.map(([k, v]) => `${indent}--sm-${kebab(k)}: ${v};`).join('\n');
const light = block('light');
const dark = block('dark');

const css = `/* Generated by packages/ui/scripts/build-css.mjs from tokens.ts — do not edit by hand. */
:root {
${vars(light, '  ')}
  --sm-radius-sm: 6px;
  --sm-radius-md: 10px;
  --sm-radius-lg: 16px;
  --sm-touch: 48px;
  --sm-motion: 180ms;
  --sm-text-scale: 1;
  color-scheme: light;
}

[data-theme="dark"] {
${vars(dark, '  ')}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${vars(dark, '    ')}
    color-scheme: dark;
  }
}

/* High-contrast toggle: secondary text and borders become full strength. */
[data-contrast="high"] {
  --sm-muted: var(--sm-text);
  --sm-border: var(--sm-border-strong);
  --sm-bg: var(--sm-surface);
}

[data-text-size="large"] {
  --sm-text-scale: 1.2;
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --sm-motion: 0ms;
  }
}

/* Tailwind v4 theme bridge: utilities like bg-brand / text-muted read the live variables. */
@theme inline {
${light.map(([k]) => `  --color-${kebab(k)}: var(--sm-${kebab(k)});`).join('\n')}
  --radius-sm: var(--sm-radius-sm);
  --radius-md: var(--sm-radius-md);
  --radius-lg: var(--sm-radius-lg);
  --font-sans: var(--sm-font, "Noto Sans"), system-ui, sans-serif;
}
`;
writeFileSync(join(here, '../src/tokens.css'), css);
console.log('tokens.css written');
