"""initial schema

Revision ID: b1d7d200abb5
Revises: 
Create Date: 2026-09-16 20:41:38.572786
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base
from alembic import op

revision: str = 'b1d7d200abb5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('step', sa.String(length=24), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('scheme_code', sa.String(length=48), nullable=True),
    sa.Column('partner_type', sa.String(length=12), nullable=True),
    sa.Column('social_category', sa.String(length=24), nullable=True),
    sa.Column('gender', sa.String(length=12), nullable=True),
    sa.Column('bucketed_age', sa.String(length=8), nullable=True),
    sa.Column('bucketed_income', sa.String(length=12), nullable=True),
    sa.Column('reason_code', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_ts'), ['ts'], unique=False)

    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('id', name=op.f('uq_audit_log_id'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity'), ['entity'], unique=False)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_feature_flags'))
    )
    op.create_table('offline_submissions',
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_via', sa.String(length=8), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_submissions')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_offline_submissions_client_uuid'))
    )
    op.create_table('otp_challenges',
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('locked_until', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_phone_hash'), ['phone_hash'], unique=False)

    op.create_table('partners',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('district_code', sa.String(length=8), nullable=False),
    sa.Column('district_name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=240), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('service_radius_km', sa.Integer(), nullable=False),
    sa.Column('schemes_supported', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('categories_supported', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('documents_needed', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('open_hours', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_state_code'), ['state_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_type'), ['type'], unique=False)

    op.create_table('schemes',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('apex_corp', sa.String(length=16), nullable=False),
    sa.Column('name_i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('loan_type', sa.String(length=24), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes')),
    sa.UniqueConstraint('code', name=op.f('uq_schemes_code'))
    )
    op.create_table('sms_inbound_parts',
    sa.Column('sender_hash', sa.String(length=64), nullable=False),
    sa.Column('message_ref', sa.String(length=8), nullable=False),
    sa.Column('part_no', sa.Integer(), nullable=False),
    sa.Column('part_total', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_inbound_parts')),
    sa.UniqueConstraint('sender_hash', 'message_ref', 'part_no', name=op.f('uq_sms_inbound_parts_sender_hash'))
    )
    with op.batch_alter_table('sms_inbound_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_inbound_parts_sender_hash'), ['sender_hash'], unique=False)

    op.create_table('partner_metrics',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=False),
    sa.Column('npa_pct', sa.Float(), nullable=False),
    sa.Column('avg_sanction_days', sa.Float(), nullable=False),
    sa.Column('funds_allocated_paise', sa.BigInteger(), nullable=False),
    sa.Column('funds_disbursed_paise', sa.BigInteger(), nullable=False),
    sa.Column('pending_applications', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_metrics_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'period', name=op.f('pk_partner_metrics'))
    )
    op.create_table('scheme_rule_versions',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_url', sa.String(length=300), nullable=False),
    sa.Column('verified_on', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_scheme_rule_versions_scheme_id_schemes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_rule_versions')),
    sa.UniqueConstraint('scheme_id', 'version', name=op.f('uq_scheme_rule_versions_scheme_id'))
    )
    with op.batch_alter_table('scheme_rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_rule_versions_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('users',
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('preferred_lang', sa.String(length=8), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('csc_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_users_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_hash', name=op.f('uq_users_phone_hash'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('applicants',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_operator_id', sa.Uuid(), nullable=True),
    sa.Column('full_name_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('father_name_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('name_normalized', sa.String(length=160), nullable=True),
    sa.Column('name_phonetic', sa.String(length=160), nullable=True),
    sa.Column('dob_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('phone_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('address_enc', app.db.base.EncryptedText(), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=12), nullable=True),
    sa.Column('social_category', sa.String(length=24), nullable=True),
    sa.Column('disability_flag', sa.Boolean(), nullable=False),
    sa.Column('disability_pct', sa.Integer(), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('annual_family_income_paise', sa.BigInteger(), nullable=True),
    sa.Column('education_level', sa.String(length=24), nullable=True),
    sa.Column('occupation', sa.String(length=48), nullable=True),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('consent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_operator_id'], ['users.id'], name=op.f('fk_applicants_created_by_operator_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applicants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applicants'))
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applicants_aadhaar_hash'), ['aadhaar_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_applicants_created_by_operator_id'), ['created_by_operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applicants_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('tracking_id', sa.String(length=20), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=True),
    sa.Column('rule_version_id', sa.Uuid(), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('requested_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('project_cost_paise', sa.BigInteger(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('moratorium_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate_bps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('eligibility_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ranking_explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('finance_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('submitted_via', sa.String(length=8), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('rejection_reason_code', sa.String(length=32), nullable=True),
    sa.Column('requested_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_applications_applicant_id_applicants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_applications_partner_id_partners')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_applications_scheme_id_schemes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_applications_client_uuid')),
    sa.UniqueConstraint('tracking_id', name=op.f('uq_applications_tracking_id'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index('ix_applications_status_open', ['status'], unique=False)

    op.create_table('consents',
    sa.Column('applicant_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('text_version', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('captured_by_operator_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_consents_applicant_id_applicants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_table('conversations',
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('turns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('extracted_slots', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pending_slot', sa.String(length=32), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_conversations_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('documents',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=160), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ocr_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('purge_after', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('purged_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_application_id'), ['application_id'], unique=False)

    op.create_table('notifications',
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('to_hash', sa.String(length=64), nullable=True),
    sa.Column('to_masked', sa.String(length=16), nullable=True),
    sa.Column('template_id', sa.String(length=48), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('segments', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_msg_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_notifications_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_application_id'))

    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('consents')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_status_open')
        batch_op.drop_index(batch_op.f('ix_applications_partner_id'))
        batch_op.drop_index(batch_op.f('ix_applications_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applicant_id'))

    op.drop_table('applications')
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applicants_user_id'))
        batch_op.drop_index(batch_op.f('ix_applicants_created_by_operator_id'))
        batch_op.drop_index(batch_op.f('ix_applicants_aadhaar_hash'))

    op.drop_table('applicants')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('scheme_rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_rule_versions_scheme_id'))

    op.drop_table('scheme_rule_versions')
    op.drop_table('partner_metrics')
    with op.batch_alter_table('sms_inbound_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_inbound_parts_sender_hash'))

    op.drop_table('sms_inbound_parts')
    op.drop_table('schemes')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_type'))
        batch_op.drop_index(batch_op.f('ix_partners_state_code'))

    op.drop_table('partners')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_phone_hash'))

    op.drop_table('otp_challenges')
    op.drop_table('offline_submissions')
    op.drop_table('feature_flags')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity'))

    op.drop_table('audit_log')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_ts'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
